.gitignore, package-lock.json, package.json, package/communication/communicate.communicator.ts, package/communication/email/email.communication.ts, package/communication/sms/sms.communication.ts, package/communication/whatsapp/whatsapp.communication.ts, package/package-lock.json, package/package.json, package/registry/ControllersRegistry.ts, package/registry/FunctionsRegistry.ts, package/validation/default.validation.ts
Merge development branch into main branch
=> Merge development into main

package/config/provider.config.ts, package/database/provider.database.ts
database  connection fix host
Ref: #25
---
=> fix: :ambulance: database connection fix

package/middlewares/fileHandler.middleware.ts, package/utils/upload.utils.ts
multer and S3Client type checking fix
Ref: #38
---
=> fix(utils): fix type error

package/middlewares/fileHandler.middleware.ts, package/utils/upload.utils.ts
=> merge: from Development

package-lock.json, package.json
@types/multer and @types/multer-s3 added to package.json
Ref: #38
---
=> feat: package json update

package/index.ts, package/modules/_system/controllers.registry.ts, package/modules/_system/controllers/_system.controller.ts, package/modules/_system/routes.registry.ts, package/registry/RoutesRegistry.ts, package/registry/index.ts, package/route/setup.route.ts
=> enhancement: version api added to service-core

package-lock.json, package.json, package/communication/sms/sms.communication.ts, package/communication/whatsapp/whatsapp.communication.ts, package/package-lock.json, package/package.json
node-fetch to node-fetch-commonjs converted and impact handled
Ref #no-issue
---
=> fix(core): :bug: node-fetch package issue resolved

package/route/setup.route.ts
setupLandingRoute function call order fix
Ref: no-issue
---
=> fix: :bug: default landing route order fix

package/route/setup.landing.route.ts
fix default landing pages call for not present API
Ref: #62
---
=> fix: :bug: fix default landing pages

package/config/types.config.ts
fix type missing for new key added in config file
Ref: #65
---
=> fix(global): :zap: fix type missing

package/database/actions.database.ts
database action findByPk fix
Ref: #54
---
=> feat(global): :sparkles: database action findByPk fix

package/modules/_system/controllers/database.controller.ts
get table attributes fix
Ref: #77
---
=> fix(global): :bug: get table attributes API fix

CHANGELOG.md, package-lock.json, package.json, package/modules/_system/controllers/database.controller.ts, package/package-lock.json, package/package.json
=> merge: development into main

.github/workflows/pr-guardrails.yml
Fix pr guardrails config, eslint now doesn't tries to lints deleted files
#80
---
=> ci(config): :bug: fix pr-guardrails eslint

package/models/Pages.model.ts
pages model new column layout added
Ref: #83
---
=> feat(global): :sparkles: pages model added new column

package-lock.json, package.json, package/coreApp.ts, package/index.ts, package/package-lock.json, package/package.json
coreApp handle all service core function calling
Ref: #85
---
=> feat(global): :zap: wrappidApp is replaced with coreApp

package-lock.json, package.json
update package json  missing package types/cors
Ref: #85
---
=> fix(global): update package json

package/modules/_system/controllers/business.controller.ts, package/modules/_system/controllers/database.controller.ts, package/modules/_system/functions/formSchema.helper.ts
fix business and formshemas api
Ref: #19
---
=> fix(global): :bug: fix business and formshemas api

package/modules/_system/controllers/forms.controller.ts, package/modules/_system/functions/formSchema.helper.ts
=> bugfix: noauth/formSchema/:formID api fix

package-lock.json, package.json, package/middlewares/fileHandler.middleware.ts, package/utils/upload.utils.ts
upload middleware fix
Ref: #93
---
=> fix(global): :bug: upload middleware fix

package/app.ts, package/index.ts
modification in app and index file
Ref: #95
---
=> perf(global): :sparkles: modification in app and index file

package/modules/_system/controllers.registry.ts, package/modules/_system/controllers/data.controller.ts, package/modules/_system/functions/data.function.ts, package/modules/_system/routes.registry.ts
=> feat(global): :sparkles: data API added

package/utils/routes.utils.ts
fix version not coming
Ref: #98
---
=> fix: fix version not coming

package/communication/communicate.communicator.ts, package/communication/email/email.communication.ts, package/communication/sms/sms.communication.ts, package/communication/whatsapp/whatsapp.communication.ts, package/config/types.config.ts, package/utils/communication.utils.ts
communication enable or disabled handling
Ref: #102
---
=> feat(global): :sparkles: communication enable or disable feature added

ATTRIBUTIONS.md, scripts/attributions.gen.js
Add functionality in attribution generation script to add fixed header.
#105
=> enhancement: header in attribution script

package-lock.json, package.json, package/app.ts, package/logging/setup.logging.ts, package/modules/_system/controllers/business.controller.ts
logging differnt level for winston
Ref: #107
---
=> feat(global): :sparkles: winston logging

package-lock.json, package.json, package/communication/communicate.communicator.ts, package/communication/whatsapp/whatsapp.communication.ts, package/modules/_system/controllers.registry.ts, package/modules/_system/controllers/_system.controller.ts, package/modules/_system/functions/_system.function.ts, package/modules/_system/routes.registry.ts, package/modules/_system/utils/_system.utils.ts, package/modules/_system/validations/_system.validation.ts
=> enhancement: create test route for communication

package/package-lock.json, package/package.json
update package json inside package folder with express-winston and winston
Ref: #107
---
=> feat(global): :wrench: update package json inside package folder

package/database/actions.database.ts
all database action add a parameter transaction
Ref: #113
---
=> feat(global): :zap: database action fix

package/logging/setup.logging.ts, package/modules/_system/controllers.registry.ts, package/modules/_system/controllers/_system.controller.ts, package/modules/_system/functions/_system.function.ts, package/modules/_system/validations/_system.validation.ts
masterdata api moved to service-core form data-management
Ref: #117
---
=> feat(global): :sparkles: masterdata api moved to service-core

package-lock.json, package.json, package/config/types.config.ts, package/constants/server.constant.ts, package/index.ts, package/logging/setup.logging.ts, package/package-lock.json, package/package.json, package/payment/payment.action.ts, package/payment/razorpay/razorpay.payment.action.ts
=> enhancement: razorpay integration

package/models/Pages.model.ts
added a new column in Pages Model
Ref: #120
---
=> feat(global): :sparkles: added a new column in Pages Model

package/modules/_system/controllers.registry.ts, package/modules/_system/controllers/data.controller.ts, package/modules/_system/functions/data.function.ts, package/modules/_system/routes.registry.ts
remove database params from data API
Ref: #122
---
=> fix(global): :bug: remove database params from data API

package/modules/_system/models.registry.ts, package/modules/_system/models/ThemeSchemas.model.ts
themeSchema model added in service-core
Ref: #124
---
=> enhancement: themeSchema model added in service-core

package/modules/_system/controllers/data.controller.ts, package/modules/_system/functions/data.function.ts
post data model return error fix
Ref: #126
---
=> fix(global): :bug: post data model return error fix

package/route/setup.landing.route.ts
landing page auther key change
Ref: #25
---
=> fix(global): :bug: auther key change

package/constants/server.constant.ts, package/modules/_system/controllers.registry.ts, package/modules/_system/controllers/data.controller.ts, package/modules/_system/functions/data.function.ts, package/modules/_system/routes.registry.ts, package/types/generic.types.ts
This will fixed the data related api(s).
#128 
---
=> enhancement: fixed the data related api(s)

.eslintrc.js, .gitignore, package-lock.json, package.json
This PR adds es-lint config, to restrict undocumented source code.
Ref: #136 
This PR is expected to fail at code style check. As code contains undocumented code.
---
=> enforce eslint config to restrict undocumented code.

package/app.ts, package/constants/server.constant.ts, package/context/application.context.ts, package/modules/_system/functions/data.function.ts, package/modules/_system/functions/formSchema.helper.ts, package/modules/_system/functions/registry.function.ts, package/modules/_system/routes.registry.ts, package/utils/yupValidationSchema.ts
=> enhancement:  registry data api add

package/app.ts, package/index.ts, package/registry/setup.registry.ts
app.ts code change to class style
Ref: #138
---
=> refactor(global): :recycle: app.ts code change to class style

package/package-lock.json, package/package.json
add axios in package/package.json
#142
---
=> bugfix(config): :package: add missing package axios

package-lock.json, package.json, package/package-lock.json, package/package.json
update package json with supertest/types package and add supertest inside package folder package json file
Ref: #144
---
=> chore(global): :bug: update package json with supertest/types package

package-lock.json, package.json, package/config/provider.config.ts, package/index.ts, package/package-lock.json, package/package.json, package/registry/setup.registry.ts
setup routes fix for databse routes
Ref: #144
---
=> fix(global): :bug: fix routes setup

package-lock.json, package.json, package/middlewares/jwtVerify.middleware.ts
jwt validation fix accessTokenSecret
Ref: #150
---
=> fix(global): :bug: jwt validation fix

package/registry/setup.registry.ts
read from db routes destructuring  fix
Ref: #152
---
=> fix(global): :bug: read from db routes destructuring  fix

package/database/Book.model.json, package/database/ModelSchemas.model.json, package/database/generic.model.ts, package/database/setup.database.ts, package/database/setup.models.database.ts, package/index.ts, package/models/Pages.model.ts, package/models/model_Json/ApiRequestLogs.model.json, package/models/model_Json/Applications.model.json, package/models/model_Json/CommunicationHistories.model.json, package/models/model_Json/CommunicationTemplates.model.json, package/models/model_Json/CronSchemas.model.json, package/models/model_Json/DataTableOptions.model.json, package/models/model_Json/MasterData.model.json, package/models/model_Json/Otp.model.json, package/models/model_Json/Pages.model.json, package/models/model_Json/Routes.model.json, package/models/model_Json/SettingMeta.model.json, package/models/model_Json/StringValues.model.json, package/models/model_Json/SupportedLanguages.model.json, package/modules/_system/functions/businessEntity.helper.ts, package/modules/_system/models.registry.ts, package/modules/_system/models/model_json/BusinessEntitySchemas.model.json, package/modules/_system/models/model_json/FormSchemas.model.json, package/modules/_system/models/model_json/ThemeSchemas.model.json, package/registry/ModelsRegistry.ts
=> enhancement: model json to model sequelize instance creation

package/WrappidApp.ts, package/database/setup.database.ts, package/database/setup.models.database.ts, package/models/model_Json/Routes.model.json, package/modules/_system/functions/data.function.ts
fix setup model from database calling async function
Ref: #158
---
=> fix(global): :bug: fix setupmodel from database

package/database/setup.models.database.ts, package/modules/_system/functions/data.function.ts
data clone fix  commitId added and authRequired removed
Ref: #158
---
=> fix(global): :ambulance: data clone fix

package/modules/_system/functions/data.function.ts, package/modules/_system/routes.registry.ts
routes registry a system field add
Ref: #161
---
=> feat(global): :sparkles: routes registry a system field add

package/models/Pages.model.ts, package/models/Routes.models.ts, package/models/model_Json/Pages.model.json, package/models/model_Json/Routes.model.json, package/modules/_system/controllers.registry.ts, package/modules/_system/controllers/database.controller.ts, package/modules/_system/functions/data.function.ts, package/modules/_system/models/BusinessEntitySchemas.model.ts, package/modules/_system/models/FormSchemas.model.ts, package/modules/_system/models/ThemeSchemas.model.ts, package/modules/_system/models/model_json/BusinessEntitySchemas.model.json, package/modules/_system/models/model_json/FormSchemas.model.json, package/modules/_system/models/model_json/ThemeSchemas.model.json, package/modules/_system/routes.registry.ts
new API to get all databases
Ref: #163
---
=> feat(global): :sparkles: new API to get all databases

package/modules/_system/functions/data.function.ts
putDatabaseModel fix
Ref: #163
---
=> fix(global): :bug: putDatabaseModel fix

.eslintrc.js
set jsdoc to error if function documentation not written
#167
=> ci(config): :bug: jsdoc lint issue

package/WrappidApp.ts, package/context/application.context.ts, package/database/setup.models.database.ts, package/registry/setup.registry.ts, package/swagger/swagger-generate.ts, package/swagger/swagger.setup.ts
Created a generic Swagger Generate functionality which fetches data from database and populated the swagger json
#169 It resolves this issue
@techoneel
=> Wrpd enhancement 169

package/swagger/swagger-generate.ts
swagger generator fix
Ref: #172
---
=> fix(global): :bug: swagger generator fix

package/utils/upload.utils.ts
Handle error case fileHandler middleware, in upload.utils.ts where no file input from request and document upload.utils.ts
#174
---
=> fix(core): :bug: handle case of fileHandler middleware where no file input from request

package/modules/_system/functions/data.function.ts
fixed update data API
Ref: #176
---
=> fix(core): :bug: fixed update data API

package/modules/_system/functions/formSchema.helper.ts
fix noauth formSchema
Ref: #178
---
=> fix(global): :bug: fix noauth formSchema

package/utils/upload.utils.ts
upload file type added doc and pdf
Ref: #180
---
=> feat(core): :sparkles: upload file type added doc and pdf
